import Providers from "@/lib/react-query/providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="px-[1.5rem] sm:px-[4rem] py-8">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
